/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq;


import info.galudisu.pg.jooq.tables.Courses;
import info.galudisu.pg.jooq.tables.Exams;
import info.galudisu.pg.jooq.tables.Students;
import info.galudisu.pg.jooq.tables.records.CoursesRecord;
import info.galudisu.pg.jooq.tables.records.ExamsRecord;
import info.galudisu.pg.jooq.tables.records.StudentsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CoursesRecord> COURSES_PKEY = UniqueKeys0.COURSES_PKEY;
    public static final UniqueKey<ExamsRecord> PK = UniqueKeys0.PK;
    public static final UniqueKey<StudentsRecord> STUDENTS_PKEY = UniqueKeys0.STUDENTS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ExamsRecord, StudentsRecord> EXAMS__EXAMS_S_ID_FKEY = ForeignKeys0.EXAMS__EXAMS_S_ID_FKEY;
    public static final ForeignKey<ExamsRecord, CoursesRecord> EXAMS__EXAMS_C_NO_FKEY = ForeignKeys0.EXAMS__EXAMS_C_NO_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CoursesRecord> COURSES_PKEY = Internal.createUniqueKey(Courses.COURSES, "courses_pkey", new TableField[] { Courses.COURSES.C_NO }, true);
        public static final UniqueKey<ExamsRecord> PK = Internal.createUniqueKey(Exams.EXAMS, "pk", new TableField[] { Exams.EXAMS.S_ID, Exams.EXAMS.C_NO }, true);
        public static final UniqueKey<StudentsRecord> STUDENTS_PKEY = Internal.createUniqueKey(Students.STUDENTS, "students_pkey", new TableField[] { Students.STUDENTS.S_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ExamsRecord, StudentsRecord> EXAMS__EXAMS_S_ID_FKEY = Internal.createForeignKey(Keys.STUDENTS_PKEY, Exams.EXAMS, "exams_s_id_fkey", new TableField[] { Exams.EXAMS.S_ID }, true);
        public static final ForeignKey<ExamsRecord, CoursesRecord> EXAMS__EXAMS_C_NO_FKEY = Internal.createForeignKey(Keys.COURSES_PKEY, Exams.EXAMS, "exams_c_no_fkey", new TableField[] { Exams.EXAMS.C_NO }, true);
    }
}
