/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq;


import info.galudisu.pg.jooq.tables.Courses;
import info.galudisu.pg.jooq.tables.Exams;
import info.galudisu.pg.jooq.tables.Students;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1011800990;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.courses</code>.
     */
    public final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>public.exams</code>.
     */
    public final Exams EXAMS = Exams.EXAMS;

    /**
     * The table <code>public.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Courses.COURSES,
            Exams.EXAMS,
            Students.STUDENTS);
    }
}
