/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq;


import info.galudisu.pg.jooq.tables.Courses;
import info.galudisu.pg.jooq.tables.Exams;
import info.galudisu.pg.jooq.tables.Students;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.courses</code>.
     */
    public static final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>public.exams</code>.
     */
    public static final Exams EXAMS = Exams.EXAMS;

    /**
     * The table <code>public.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;
}
