/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq.tables.daos;


import info.galudisu.pg.jooq.tables.Courses;
import info.galudisu.pg.jooq.tables.records.CoursesRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoursesDao extends DAOImpl<CoursesRecord, info.galudisu.pg.jooq.tables.pojos.Courses, String> {

    /**
     * Create a new CoursesDao without any configuration
     */
    public CoursesDao() {
        super(Courses.COURSES, info.galudisu.pg.jooq.tables.pojos.Courses.class);
    }

    /**
     * Create a new CoursesDao with an attached configuration
     */
    public CoursesDao(Configuration configuration) {
        super(Courses.COURSES, info.galudisu.pg.jooq.tables.pojos.Courses.class, configuration);
    }

    @Override
    public String getId(info.galudisu.pg.jooq.tables.pojos.Courses object) {
        return object.getCNo();
    }

    /**
     * Fetch records that have <code>c_no BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<info.galudisu.pg.jooq.tables.pojos.Courses> fetchRangeOfCNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Courses.COURSES.C_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>c_no IN (values)</code>
     */
    public List<info.galudisu.pg.jooq.tables.pojos.Courses> fetchByCNo(String... values) {
        return fetch(Courses.COURSES.C_NO, values);
    }

    /**
     * Fetch a unique record that has <code>c_no = value</code>
     */
    public info.galudisu.pg.jooq.tables.pojos.Courses fetchOneByCNo(String value) {
        return fetchOne(Courses.COURSES.C_NO, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<info.galudisu.pg.jooq.tables.pojos.Courses> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Courses.COURSES.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<info.galudisu.pg.jooq.tables.pojos.Courses> fetchByTitle(String... values) {
        return fetch(Courses.COURSES.TITLE, values);
    }

    /**
     * Fetch records that have <code>hours BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<info.galudisu.pg.jooq.tables.pojos.Courses> fetchRangeOfHours(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Courses.COURSES.HOURS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>hours IN (values)</code>
     */
    public List<info.galudisu.pg.jooq.tables.pojos.Courses> fetchByHours(Integer... values) {
        return fetch(Courses.COURSES.HOURS, values);
    }
}
