language: java
jdk:
  - openjdk8

services:
  - postgresql

addons:
  chrome: stable
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12


before_install:
  - psql -c "CREATE USER app WITH PASSWORD 'p@ssw0rd' ;" -U postgres
  - psql -c "CREATE DATABASE appdb owner app ;" -U postgres
  - psql -c "GRANT CONNECT ON DATABASE appdb TO app ;" -U postgres
  - chmod +x mvnw

before_script:
  - PASSWORD='p@ssw0rd' psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app ;" -U app appdb
  - PASSWORD='p@ssw0rd' psql --dbname=appdb --file=init.sql -U app appdb

script:
  - mvn clean test jacoco:report

after_success:
  - travis_wait mvn site
  - bash <(curl -s https://codecov.io/bash)