language: java
jdk:
  - openjdk8

services:
  - postgresql

before_install:
  - psql -c "CREATE USER app WITH PASSWORD 'p@ssw0rd' ;" -U postgres
  - psql -c "CREATE DATABASE appdb owner app ;" -U postgres
  - psql -c "GRANT CONNECT ON DATABASE appdb TO app ;" -U postgres
  - psql -c "CREATE EXTENSION IF NOT EXISTS 'uuid-ossp';" -U postgres appdb
  - chmod +x mvnw

before_script:
  - PASSWORD='p@ssw0rd' psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app ;" -U app appdb
  - PASSWORD='p@ssw0rd' psql --dbname=appdb --file=init.sql -U app appdb

script:
  - mvn clean test jacoco:report

after_success:
  - travis_wait mvn site
  - bash <(curl -s https://codecov.io/bash)