language: java
jdk:
  - openjdk8

services:
  - postgresql

env:
  global:
    - PGDATABASE=appdb
    - PGUSER=app
    - PGPASS='p@ssw0rd'

before_install:
  - psql -c "CREATE USER $PGUSER WITH PASSWORD $PGPASS ;" -U postgres
  - psql -c "CREATE DATABASE $PGDATABASE owner $PGUSER ;" -U postgres
  - chmod +x mvnw

before_script:
  - PASSWORD=$PGPASS psql -c "GRANT CONNECT ON DATABASE $PGDATABASE TO $PGUSER ;" -U $PGUSER
  - PASSWORD=$PGPASS psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $PGUSER ;" -U $PGUSER
  - PASSWORD=$PGPASS psql --dbname=$PGDATABASE --file=init.sql -U $PGUSER

script:
  - mvn clean test jacoco:report

after_success:
  - travis_wait mvn site
  - bash <(curl -s https://codecov.io/bash)