language: java
jdk:
  - openjdk8

addons:
  postgresql: "12.3"


services:
  - postgresql

before_install:
  - psql -c "CREATE USER app WITH PASSWORD 'p@ssw0rd' ;" -U postgres
  - psql -c "CREATE DATABASE appdb ;" -U postgres
  - psql -c "GRANT CONNECT ON DATABASE appdb TO app ;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app ;" -U postgres
-U postgres
  - psql --dbname=appdb --file=init.sql
  - chmod +x mvnw

script:
  - mvn clean test jacoco:report

after_success:
  - travis_wait mvn site
  - bash <(curl -s https://codecov.io/bash)