/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Courses implements Serializable {

    private static final long serialVersionUID = -1725434715;

    private String  cNo;
    private String  title;
    private Integer hours;

    public Courses() {}

    public Courses(Courses value) {
        this.cNo = value.cNo;
        this.title = value.title;
        this.hours = value.hours;
    }

    public Courses(
        String  cNo,
        String  title,
        Integer hours
    ) {
        this.cNo = cNo;
        this.title = title;
        this.hours = hours;
    }

    public String getCNo() {
        return this.cNo;
    }

    public void setCNo(String cNo) {
        this.cNo = cNo;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getHours() {
        return this.hours;
    }

    public void setHours(Integer hours) {
        this.hours = hours;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Courses other = (Courses) obj;
        if (cNo == null) {
            if (other.cNo != null)
                return false;
        }
        else if (!cNo.equals(other.cNo))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (hours == null) {
            if (other.hours != null)
                return false;
        }
        else if (!hours.equals(other.hours))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.cNo == null) ? 0 : this.cNo.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.hours == null) ? 0 : this.hours.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Courses (");

        sb.append(cNo);
        sb.append(", ").append(title);
        sb.append(", ").append(hours);

        sb.append(")");
        return sb.toString();
    }
}
