/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exams implements Serializable {

    private static final long serialVersionUID = 789384336;

    private Integer sId;
    private String  cNo;
    private Integer score;

    public Exams() {}

    public Exams(Exams value) {
        this.sId = value.sId;
        this.cNo = value.cNo;
        this.score = value.score;
    }

    public Exams(
        Integer sId,
        String  cNo,
        Integer score
    ) {
        this.sId = sId;
        this.cNo = cNo;
        this.score = score;
    }

    public Integer getSId() {
        return this.sId;
    }

    public void setSId(Integer sId) {
        this.sId = sId;
    }

    public String getCNo() {
        return this.cNo;
    }

    public void setCNo(String cNo) {
        this.cNo = cNo;
    }

    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Exams other = (Exams) obj;
        if (sId == null) {
            if (other.sId != null)
                return false;
        }
        else if (!sId.equals(other.sId))
            return false;
        if (cNo == null) {
            if (other.cNo != null)
                return false;
        }
        else if (!cNo.equals(other.cNo))
            return false;
        if (score == null) {
            if (other.score != null)
                return false;
        }
        else if (!score.equals(other.score))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.sId == null) ? 0 : this.sId.hashCode());
        result = prime * result + ((this.cNo == null) ? 0 : this.cNo.hashCode());
        result = prime * result + ((this.score == null) ? 0 : this.score.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Exams (");

        sb.append(sId);
        sb.append(", ").append(cNo);
        sb.append(", ").append(score);

        sb.append(")");
        return sb.toString();
    }
}
