/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students implements Serializable {

    private static final long serialVersionUID = 1862075948;

    private Integer sId;
    private String  name;
    private Integer startYear;

    public Students() {}

    public Students(Students value) {
        this.sId = value.sId;
        this.name = value.name;
        this.startYear = value.startYear;
    }

    public Students(
        Integer sId,
        String  name,
        Integer startYear
    ) {
        this.sId = sId;
        this.name = name;
        this.startYear = startYear;
    }

    public Integer getSId() {
        return this.sId;
    }

    public void setSId(Integer sId) {
        this.sId = sId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStartYear() {
        return this.startYear;
    }

    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Students other = (Students) obj;
        if (sId == null) {
            if (other.sId != null)
                return false;
        }
        else if (!sId.equals(other.sId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (startYear == null) {
            if (other.startYear != null)
                return false;
        }
        else if (!startYear.equals(other.startYear))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.sId == null) ? 0 : this.sId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.startYear == null) ? 0 : this.startYear.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Students (");

        sb.append(sId);
        sb.append(", ").append(name);
        sb.append(", ").append(startYear);

        sb.append(")");
        return sb.toString();
    }
}
