/*
 * This file is generated by jOOQ.
 */
package info.galudisu.pg.jooq.tables;


import info.galudisu.pg.jooq.Keys;
import info.galudisu.pg.jooq.Public;
import info.galudisu.pg.jooq.tables.records.ExamsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exams extends TableImpl<ExamsRecord> {

    private static final long serialVersionUID = -1877847021;

    /**
     * The reference instance of <code>public.exams</code>
     */
    public static final Exams EXAMS = new Exams();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExamsRecord> getRecordType() {
        return ExamsRecord.class;
    }

    /**
     * The column <code>public.exams.s_id</code>.
     */
    public final TableField<ExamsRecord, Integer> S_ID = createField(DSL.name("s_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.exams.c_no</code>.
     */
    public final TableField<ExamsRecord, String> C_NO = createField(DSL.name("c_no"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.exams.score</code>.
     */
    public final TableField<ExamsRecord, Integer> SCORE = createField(DSL.name("score"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.exams</code> table reference
     */
    public Exams() {
        this(DSL.name("exams"), null);
    }

    /**
     * Create an aliased <code>public.exams</code> table reference
     */
    public Exams(String alias) {
        this(DSL.name(alias), EXAMS);
    }

    /**
     * Create an aliased <code>public.exams</code> table reference
     */
    public Exams(Name alias) {
        this(alias, EXAMS);
    }

    private Exams(Name alias, Table<ExamsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Exams(Name alias, Table<ExamsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Exams(Table<O> child, ForeignKey<O, ExamsRecord> key) {
        super(child, key, EXAMS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ExamsRecord> getPrimaryKey() {
        return Keys.PK;
    }

    @Override
    public List<UniqueKey<ExamsRecord>> getKeys() {
        return Arrays.<UniqueKey<ExamsRecord>>asList(Keys.PK);
    }

    @Override
    public List<ForeignKey<ExamsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExamsRecord, ?>>asList(Keys.EXAMS__EXAMS_S_ID_FKEY, Keys.EXAMS__EXAMS_C_NO_FKEY);
    }

    public Students students() {
        return new Students(this, Keys.EXAMS__EXAMS_S_ID_FKEY);
    }

    public Courses courses() {
        return new Courses(this, Keys.EXAMS__EXAMS_C_NO_FKEY);
    }

    @Override
    public Exams as(String alias) {
        return new Exams(DSL.name(alias), this);
    }

    @Override
    public Exams as(Name alias) {
        return new Exams(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Exams rename(String name) {
        return new Exams(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Exams rename(Name name) {
        return new Exams(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
